eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /user/**
      serviceId: service-ribbon
    api-b:
      path: /root/**
      serviceId: service-ribbon-admin
