eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-ribbon-admin
  resources:
    static-locations: classpath:/templates
